### ISSUE TITLE
Create docs with purposeful examples

### ISSUE THREAD

**Issue by janet-can** [sodadata/docs#10]
Add docs that present copy+paste-able examples of tests for specific things.

Some things to have in there:
Row by row comparison of fields in 2 datasets, joined by 1 or more keys
Allowable value check to reference another dataset
Consistency over time

**Comment by janet-can** [comment]
A. Row-by-row comparison of fields in 2 datasets joined by 1 or more keys

We check if values in a column remain relatively stable over time. Do this by calculating the difference between today's value and yesterday's value. If the difference is bigger than a configurable threshold, the value is considered bad.
The threshold for the day-over-day comparison is 20%.

Day 1 
|id_column | value_column|
|-- | --|
|a | 10|
|b|20|
|c|30 | 

Day 2, tests pass
|id_column | value_column|
|----|----|
| a | 11 | 
|b | 16 | 
|c | 30|

**Comment by janet-can** [comment]
B. Structural validity

Test if the values in a column are valid.  Static validity means that each value can be tested independently. Examples:

- String, min length 6, max length 100. 
- Values should be non-negative numbers
- Integer, Min, Max
- Decimal, Min decimals, Max decimals
- Boolean

**Comment by janet-can** [comment]
C. Dynamic validity 

Test validity of a column value based on other values in the dataset. The test result is based on the whole column.  The test fails if the percentage of invalid values exceeds the threshold.

- For each item identified as PackageA, the weight should be between 3 - 6 kilos. 
- For each item identified as PackageB, the weight should be between 1 - 2 kilos.

**Comment by janet-can** [comment]
D. Missing values

Test if there are not too many missing values. Set acceptable threshold for missing values.

E. Uniqueness

Each combination of values for the columns has to be unique.Each time we run the test we count the combinations that occur multiple times. The test fails if there is one or more duplicates.

**Comment by janet-can** [comment]
F. Equivalence

Values can occur multiple times, but there should be a 1-1 relation between the columns. Similar to how you would consider country codes and country names. Each time we run the test we count the values that have inconsistent values in the other column.  In the example failing data, that is 2.  This count metric is plotted over time.

Test passes:

|col1 | col2 | ...other columns...|
|-- | -- | --|
|a | 1 |  |
|a | 1 |  |
|b | 2 |  |
|b | 2 |  |
|c | 3 |  |

Test fails:

|col1 | col2 | ...other columns...|
|-- | -- | --|
|a | 1 |  |
|a | 2 |  |
|b | 3 |  |
|x | 3 |  |
|c | 4 |  |

Value 'a' in the first column occurs with multiple values in the second column: '1' and '2'
Value '3' in the second column occurs with multiple values in the first column: 'b' and 'x'

**Comment by albinkjellin** [comment]
G.Dynamic validity - Check value against other table

Validate that each value in a table is present in another one.

| Customer Id  | Country |
| ------------- | ------------- |
| Albin  | SE  |
| Janet  | CA  |

Reference table:

| Country Codes  
| ------------- |
| SE  |
| CA  |
| BE |

**Comment by JoeriMeurisse** [comment]
A.bis Consistency over time by groups

Calculate consistency over time of subsets of the dataset, based on a grouping by field.

For example: The dataset consists of health insurance claims submitted, with the hospital where the claim originates. You want to flag any hospital that differs more than 20% in claim value submitted between submissions

Week 1:
Patient ID | Claim amount | Hospital ID
-- | -- | --
Patient 1 | 1000 | Hospital A
Patient 2 | 2000 | Hospital A
Patient 3 | 1000 | Hospital A
Patient 4 | 2000 | Hospital B
Patient 5 | 3000 | Hospital B
Patient 6 | 2000 | Hospital B

Week 2:
Patient ID | Claim amount | Hospital ID
-- | -- | --
Patient 7 | 850 | Hospital A
Patient 8 | 2000 | Hospital A
Patient 9 | 1100 | Hospital A
Patient 10 | 3000 | Hospital B
Patient 11 | 1500 | Hospital B
Patient 12 | 2500 | Hospital B
Patient 13 | 1500 | Hospital B

Hospital A passes (4000 -> 3950)
Hospital B fails ( 7000 -> 8500 = +21%)

(I don't think we currently support this type of analysis)

**Comment by JoeriMeurisse** [comment]
H. Conditional completeness

Calculate the percentage of missing values / return failed rows for missing values only when other fields meet conditions that make the field compulsory - ignoring empty fields if those conditions are not met.

Example: I have a list of customer orders, some are for store pick-up, some are for home delivery. The Address field needs to be filled for home delivery - for store pick-up it can be empty.

Order Type | Customer address
-- | -- 
Delivery | Main Street 1
Delivery | 
Pick-up | 1st Avenue 100
Pick-up |

This should return 1 failed row (row 2), or give a 25% conditional missing value result

**Comment by janet-can** [comment]
Added: 
- missing values example
- valid values example
- uniqueness example

Next: 
- reference dataset
- foreign key tests
- schema tests

**Comment by janet-can** [comment]
With a few of these done, I am closing this Issue in favor of collecting template examples in the [Test Template](https://docs.google.com/document/d/1aZpYjz0fozfnBCh5PM1l08daGIBVUuX_-8gY9TrYPoE/edit?ts=60893812#) initiative.
