### ISSUE TITLE
Add page view tracking to docs.soda.io

### ISSUE THREAD

**Issue by janet-can** [sodadata/docs#134]
It would be good to have the most basic data about the pages that readers are viewing in docs.soda.io.  

To capture this information, we ought to be able to use Segment, adding a [Javascript website source](https://app.segment.com/sodadata/sources/catalog/javascript). Once added, we can use June to create a dashboard and start monitoring viewership.

**Comment by dirkgroenen** [comment]
I've added the tracking in a separate branch, see above PR mention. Additionally I've added the Source to Segment and forwarded it to its own [June Workspace](https://app.june.so/a/2793/home). You've been added to the workspace so you should be able to set it up to your likings. 

Feel free to merge PR #135 whenever you like. Should all be good to go.
