### ISSUE TITLE
add instructions to install `soda-sql-dbt` in dbt integration docs

### ISSUE THREAD

**Issue by bastienboutonnet** [sodadata/docs#141]

**Comment by janet-can** [comment]
Hi @bastienboutonnet -- is this as straightforward as adding one step to the existing integration instructions? Let me know if there's more to it!

**Comment by bastienboutonnet** [comment]
Pretty much yes! I'm sorry I didn't actually fill in the description. But I also don't remember even writing up this issue... I'll actually open up a PR right away for this and you can put your spin on it if you like after.
