### ISSUE TITLE
Update documentation regarding env_vars

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/docs#23]
env_vars can be used for any parameter in warehouse file not just for credentials. Also, the credentials are strongly recommended to be passed as env_vars since we don't enforce that setting as of https://github.com/sodadata/soda-sql/issues/310

**Comment by janet-can** [comment]
Got it-- I modified a paragraph in the Env_vars section of the Warehouse YAML doc as follows:

"Beyond storing warehouse login credentials, you can use env_vars to securely store any parameter in the warehouse YAML file. Best practice dictates that you use env_vars to store login credentials and any other sensitive data such as API keys or tokens."
