### ISSUE TITLE
Link to Github discussions is broken

### ISSUE THREAD

**Issue by JCZuurmond** [sodadata/docs#26]
The link in [this line](https://github.com/sodadata/docs/blame/main/soda-sql/community.md#L26) does not work. I am not able to see the discussions, both here and both in the `soda-sql` repo

**Comment by vijaykiran** [comment]
Hi @JCZuurmond thanks for pointing, we have disabled the GitHub discussions because most of the activity is happening on slack, so we don’t need to check two different places. 

We will update the docs to remove links.

**Comment by janet-can** [comment]
Removed the link to GitHub discussions in docs.
