### ISSUE TITLE
Update docs for `samples limit` 

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/docs#316]
Please see https://github.com/sodadata/soda-core/pull/1464#issue-1288634989

**Comment by janet-can** [comment]
Samples limit is already documented for use with user-defined expressions: https://docs.soda.io/soda-cl/failed-rows-checks.html

@vijaykiran  In the comment on 1464, it mentioned that this applied to data source queries and table queries as well, but I'm not clear on what that is referencing. Is there some other place that samples limit should be documented for relevancy?

**Comment by janet-can** [comment]
Okay, I'm closing this for now as I believe I captured this in docs as needed. However, feel free to re-open if I'm mistaken!
