### ISSUE TITLE
Add SQLServer and DB2 support to the docs

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/docs#325]
Quick summary of SQLServer (preview) and db2 

For SQLServer : Install soda-core-sqlserver package  and configure data source as follows:

```
type: sqlserver
host: localhost
port: 1433
username: xxx
password: ...
database:
schema:
## Optional parameters
trusted_connection: false (default)
encrypt: false (default)
trust_server_certificate: false (default)
```

Note that regex based checks such as invalid values and validity format checks are not supported in SQLServer yet.

For db2 install soda-core-db2 and  configure the data source:

```
```
type: db2
host: localhost
port: 50000 
username: xxx
password: ...
database:
schema:
```

**Comment by janet-can** [comment]
Dunzo! https://github.com/sodadata/docs/pull/326
