### ISSUE TITLE
Incorrect square bracket on Metrics page at Grouped Column Metrics section description

### ISSUE THREAD

**Issue by surendrasinghs** [sodadata/docs#33]
There is an incorrect square bracket - a closed one "]" instead of an open "[" - as shown below
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/10580754/121776791-6ee13b00-cbac-11eb-9ed1-4cb94a81081c.png">

You can view the above at https://docs.soda.io/soda-sql/documentation/sql_metrics.html#grouped-column-metrics

Hope this helps

**Comment by surendrasinghs** [comment]
Also, it would be better if the reference to "Metrics groups and dependencies" is hyperlinked. I believe the incorrect square bracket caused the hyperlink to be dysfunctional as well. It should fix by fixing the opening bracket.

**Comment by surendrasinghs** [comment]
A valid example of how it should be is in the Description column below

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/10580754/121777160-2dea2600-cbae-11eb-9353-12b68c1f71a0.png">

**Comment by janet-can** [comment]
Thanks, @surendrasinghs, good catch! I have corrected this bracket and will merge shortly.
