### ISSUE TITLE
Soda Core usage statistics - addition

### ISSUE THREAD

**Issue by marcmarcc** [sodadata/docs#341]
When the machine running Soda does not have an internet connection it will throw several exceptions, starting with: "Exception while exporting Span batch.". This (ultimately) due to not being able to connect to soda.connect.io:443. Changing send_anonymous_usage_stats: from true to false resolves this error. Since it's not very obvious, and it's even harder to google it might work well to mention on this page.

**Comment by janet-can** [comment]
Thanks, @marcmarcc! I've added some troubleshooting information to that effect: https://docs.soda.io/soda-core/scan-core.html#troubleshoot

Much better. :)

**Comment by marcmarcc** [comment]
Superb, thank you!

Op 15 aug. 2022 om 21:10 heeft Janet R ***@***.***> het volgende geschreven:

﻿
Thanks, @marcmarcc! I've added some troubleshooting information to that effect: https://docs.soda.io/soda-core/scan-core.html#troubleshoot

Much better. :)
