### ISSUE TITLE
Make it clear how to get the exit code

### ISSUE THREAD

**Issue by jackdesert** [sodadata/docs#383]
On this page:
https://docs.soda.io/soda-core/programmatic.html

It says "Soda Core’s scan output includes an exit code which indicates the outcome of the scan." 

Let's show an example of how to get that exit code.

A simple snippet like this would suffice:

    exit_code = scan.execute()
    print(exit_code)

**Comment by janet-can** [comment]
Terrific suggestions, @jackdesert. I've added it to a PR in which I'm making a few adjustment for docs and will merge it shortly. Thanks for bringing this up!
