### ISSUE TITLE
Bad redirection to Checks tab in the Quick Start for Soda Core and Soda Cloud

### ISSUE THREAD

**Issue by benoitgoujon** [sodadata/docs#404]
Hi,

It looks like the UI has recently changed and as an aftermath, the documentation is wrong.

On [this page](https://docs.soda.io/soda/quick-start-soda-core.html#connect-soda-core-to-soda-cloud), step 7 of the "Connect Soda Core to Soda Cloud" section, it says "Go to your Soda Cloud account in your browser and navigate to the Checks dashboard. Review the results of your scan in Check Results.".

But from what I see, this tab is now called "Monitors". Is that right?

I don't mind creating a PR to fix the issue.

**Comment by janet-can** [comment]
Hi @benoitgoujon - thanks for noting this, although the situation is actually the reverse. Soda Cloud _used_ to display Monitors, but we have now renamed the entity to Checks. So the documentation is in fact correct, but I'm a little worried that you would still be seeing Monitors. 

Are you accessing Soda Cloud via cloud.soda.io?

**Comment by benoitgoujon** [comment]
Ok.

This morning, I had the menu you describe. And I also had the following release note.

![Screen Shot 2022-10-27 at 09 25 10](https://user-images.githubusercontent.com/57349292/198218281-1a5dc60e-4475-4df6-85c7-d1db0fff6ff9.png)

I accessed Soda Cloud via cloud.soda.io but maybe it was because it was a free trial?

I signed up on Tuesday.

**Comment by janet-can** [comment]
Ah, right, of course. We just made the newer version generally available so that was the reason why. In any event, it is all properly labeled and up-to-date now, so I will take the liberty of closing this issue. 

Do find us on [Slack](https://community.soda.io/slack), @benoitgoujon , if you have any questions as you dig into Soda Cloud!
