### ISSUE TITLE
I want to contribute for oracle connector, where should I start?

### ISSUE THREAD

**Issue by ridwanrputra** [sodadata/docs#423]
I see in the documentation there is no connector for oracle,  any idea where should I start if I want to  contribute?

**Comment by janet-can** [comment]
Hi @ridwanrputra -- that would be great!  

Would you like to contribute to docs?  Or are you interested in working on developing the Soda Core package for OracleDB?

- If the former, please see: [README.md](https://github.com/sodadata/docs#contribute)
- If the latter, we have instructions [here](https://github.com/sodadata/soda-core/blob/main/CONTRIBUTING-DATA-SOURCE.md) and I'd encourage you to reach out to our team in the #soda-core channel in our [Soda Community Slack workspace](https://community.soda.io/slack).

Thanks!
