### ISSUE TITLE
Update validity metric doc to match example

### ISSUE THREAD

**Issue by zshainsky** [sodadata/docs#531]
## Issue
The Validity Metrics doc has a typo where an example does not fit the description provided explaining that example.

### Documentation Link

- Code: https://github.com/sodadata/docs/blob/f65b6da359a6a921c7bdcf48e3acdb0d7c1357cf/soda-cl/validity-metrics.md?plain=1#L121
- Web: https://docs.soda.io/soda-cl/validity-metrics.html#specify-valid-or-invalid-values

### Existing example and description:
`Soda registers them as invalid. The check fails if Soda discovers more than five values that are not 0 or 1.`
```
checks for dim_customer:
  - invalid_count(house_owner_flag) = 0:
      valid values: ['0', '1']
```

### Suggested Change
The description should read: 
`Soda registers them as invalid. The check fails if Soda discovers more than any value that are not 0 or 1.`

**Comment by janet-can** [comment]
Thank you, @zshainsky!!
