### ISSUE TITLE
Type in soda-core programmatic page

### ISSUE THREAD

**Issue by PaoloLeonard** [sodadata/docs#539]
Hello,

There is a small typo in the header of the last paragraph:
https://docs.soda.io/soda-core/programmatic.html#save-failed-row-samples-to-an-alternate-desination

I believe it should be `Save failed row samples to an alternate destination` instead of `Save failed row samples to an alternate desination`?

**Comment by janet-can** [comment]
Thank you for pointing that out, @PaoloLeonard! Many eyes make cleaner text :)
