### ISSUE TITLE
typo and follow up on possible missing helper function?

### ISSUE THREAD

**Issue by nbixler** [sodadata/docs#560]
"checks to organize data qaulity check results by category" -> should be "quality"
c.f. https://docs.soda.io/soda-library/overview.html

programmatic scans suggest use of "scan.add_configuration_yaml_from_env_var(env_var_name="SODA_ENV")" 
but this may not actually be available

c.f. https://docs.soda.io/soda-library/programmatic.html

**Comment by janet-can** [comment]
A typo! Inconceivable! (Thank you, I have fixed that.)

Regarding the use of SODA_ENV, I'm following up with the team to find out more and will adjust as necessary. 

Thanks for bringing this up, @nbixler!

**Comment by benjamin-pirotte** [comment]
Hi! 

Can you give me more information about what you mean by 
>  programmatic scans suggest use of "scan.add_configuration_yaml_from_env_var(env_var_name="SODA_ENV")"
> but this may not actually be available

Thank you!

**Comment by nbixler** [comment]
The "add_configuration_yaml_from_env_var" is in the docs, but when I actually use it, it says it's not something Scan objects have access to, and when I do a global search for that string in github repos, it didn't turn up. Entirely possible I've missed something (and am making a mistake somewhere) but wondered if it was deprecated and the docs weren't updated to match.
