### ISSUE TITLE
Possible error in example code (Connect Soda to a local file using Dask)

### ISSUE THREAD

**Issue by robertdlangford** [sodadata/docs#571]
When running the example on the 'Connect Soda to a local file using Dask' page

https://github.com/sodadata/docs/blob/613c8531afc476860f10c76d00df08ebb7e8154f/soda/connect-file.md?plain=1#L25

I get the following error: `AttributeError: module 'dask.datasets' has no attribute 'read_csv'`

**Comment by baturayo** [comment]
Hi @robertdlangford ,

Thanks lot for pointing the issue. `dask.datasets` was changed with `dask.dataframe` in [this PR](https://github.com/sodadata/docs/pull/574/files). Please refer to new documentation.

**Comment by janet-can** [comment]
Thanks for logging the issue @robertdlangford !
