### ISSUE TITLE
missing work_group property in athena data source

### ISSUE THREAD

**Issue by abrahamvc** [sodadata/docs#662]
In athena data source: https://docs.soda.io/soda/connect-athena.html

There is no info about work_group property. I found it in source code: https://github.com/sodadata/soda-core/blob/3f8fcc7e07d53734c55ed817a513888b80a1b959/soda/athena/soda/data_sources/athena_data_source.py#L29C7-L29C7

We don't use default workgroup. So in test-connection I got: `botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the StartQueryExecution operation: You are not authorized to perform: athena:StartQueryExecution on the resource. After your AWS administrator or you have updated your permissions, please try again.`

I tried with boto3 and It was ok... so I thought it was related to workgroup... and luckly It is actually implemented 😄

**Comment by janet-can** [comment]
Thanks, @abrahamvc! Good eye!
I've added that property in [PR663](https://github.com/sodadata/docs/pull/663). Cheers!
