### ISSUE TITLE
soda-spark-df not foun

### ISSUE THREAD

**Issue by g-kannan** [sodadata/docs#664]
In the docs(https://docs.soda.io/soda/connect-spark.html#use-soda-library-with-spark-dataframes-on-databricks) its mentioned to use soda-spark-df whereas its not found and replaced with soda-core-spark-df

**Comment by janet-can** [comment]
Hi @g-kannan,
I just tested locally and was able to install soda-spark-df using the following command, which installs Soda Library for Spark dataframes: 
`pip install -i https://pypi.cloud.soda.io soda-spark-df`

However, if you use Soda Core, the OSS version of Soda Library, you can use:
`pip install soda-core-spark-df`

Hope that helps!
Thanks for the note.
