### ISSUE TITLE
Denodo documentation - configuration template enhancement

### ISSUE THREAD

**Issue by teimahu** [sodadata/docs#775]
Hi Soda developpers,

I tried to install the doc tooling with VSCode in order to create a PR, but I was not able to create a working env, sorry for this.
So I would just suggest to enhance an existing page in the documentation at this URL : https://docs.soda.io/soda/connect-denodo.html

This proposal follows those modifications made to the Denodo connection: 

- fix: https://github.com/sodadata/soda-core/pull/2065
- enhancement: https://github.com/sodadata/soda-core/pull/2066

So "database" and "sslmode" parameters could be added to the Denodo page in the documentation, such as:

> 
> ### Connection configuration reference
> Install package: `soda-denodo`
> ```
> data_source my_datasource_name:
>   type: denodo
>   username: simple
>   password: simple_pass
>   host: 127.0.0.1
>   port: 9996
>   database: my_db
>   sslmode: prefer
> ```
> 
> | Property  | Required | Notes |
> | ------------- | ------------- | ------------- |
> | type  | required  | Identify the type of data source for Soda.  |
> | username  | required  | Consider using system variables to retrieve this value securely.  |
> | password  | required  | Consider using system variables to retrieve this value securely.  |
> | host  | required  | Provide a host identifier.  |
> | port  | required  | Provide a port identifier.  |
> | database  | required  | Provide a virtual database (VDB) name.  |
> | sslmode  | optionnal  | SSL support can be: prefer (default), require, allow, disable  |

Best regards,

**Comment by janet-can** [comment]
Thanks for logging the issue, @teimahu !  I have added those parameters, and the connection_timeout one as well.
