### ISSUE TITLE
duckdb connection: incorrect attribute

### ISSUE THREAD

**Issue by sf-dcp** [sodadata/docs#788]
On [this](https://docs.soda.io/soda/connect-duckdb.html) page, the key name for a database file location appears to be incorrect as I was getting connection errors: 
<img width="768" alt="image" src="https://github.com/sodadata/docs/assets/144725249/faa79fd8-0537-45ff-ac2a-1647382b4c04">

However, when replacing `database` with `path`, the connection works.

**Comment by janet-can** [comment]
Hm, that's odd. I wonder what changed recently. Thanks for creating the issue, @sf-dcp , I'll add some context in there to indicate that one might use the key `path` instead of `database`. Maybe it is dependent on duckdb version, or..?

**Comment by janet-can** [comment]
Fixed in PR789.
