### ISSUE TITLE
No matching distribution for soda-pandas-dask

### ISSUE THREAD

**Issue by kunaljubce** [sodadata/docs#796]
In the doc [here](https://docs.soda.io/soda/connect-dask.html), it says: `Install package: soda-pandas-dask`. But when I try to do this, I get - "No matching distribution for soda-pandas-dask"

**Comment by janet-can** [comment]
Hi @kunaljubce -- I just gave it a try locally to confirm and I was able to install the package for Soda Library using this command: `pip install -i https://pypi.cloud.soda.io soda-pandas-dask`.
If you wish to use Soda Core, the OSS library, you can install with `pip install soda-core-pandas-dask`.
