### ISSUE TITLE
Changes for "Connect Soda to Dask and Pandas"

### ISSUE THREAD

**Issue by artc95** [sodadata/docs#869]
Refer to ["Connect Soda to Dask and Pandas" docs on docs.soda.io](https://docs.soda.io/soda/connect-dask.html).

Suggested changes for:

[LINES 11-13](https://github.com/sodadata/docs/blob/4a672e6c382c048278d0abe4aa61751892402ebd/soda/connect-dask.md?plain=1#L11C1-L11C184)
- indeed no connection to data source needed, but connection to Soda Cloud using API Keys is still needed? (i.e. per [invoking Soda programatically](https://docs.soda.io/soda-library/programmatic.html), in a `configuration.yml` using `scan.add_configuration_yaml_file`, or inline code using `scan.add_configuration_yaml_str`)

- proposed edit of lines 11-13:
"For use with [programmatic Soda scans](https://docs.soda.io/soda-library/programmatic.html), only.

[Define a programmatic scan](https://docs.soda.io/soda-library/programmatic.html) for the data in the DataFrames. You do not need to configure a connection to a data source, but must still configure a connection to Soda Cloud using API Keys. Refer to the following example."

------------------------------------

[LINE 47](https://github.com/sodadata/docs/blob/4a672e6c382c048278d0abe4aa61751892402ebd/soda/connect-dask.md?plain=1#L47)
- per changes for lines 11-13, code on how to "add configuration from a file or inline in code" (slightly adapted from ["Invoke Soda Library" docs](https://docs.soda.io/soda-library/programmatic.html), changed the `.yml` filepath and added comment that no connection to data source needed), should be added in the code example.

- proposed addition to code, after line 47 (i.e. after `scan.set_data_source_name("orders")`:
```
# Add configuration YAML files
#########################
# Choose one of the following to specify data source connection configurations :
# 1) From a file
scan.add_configuration_yaml_file(file_path="~/.soda/configuration.yml")
# 2) Inline in the code
# For host, use cloud.soda.io for EU region; use cloud.us.soda.io for US region
# NOTE: no connection to data source needed
scan.add_configuration_yaml_str(
    """
    soda_cloud:
      host: cloud.soda.io
      api_key_id: 2e0ba0cb-your-api-key-7b
      api_key_secret: 5wd-your-api-key-secret-aGuRg
"""
```

--------------------------------------------

[LINES 110-119](https://github.com/sodadata/docs/blob/4a672e6c382c048278d0abe4aa61751892402ebd/soda/connect-dask.md?plain=1#L110)
- package names should be `soda-pandas-dask`, not `soda-dask-pandas` ([index of packages on pypi](https://pypi.cloud.soda.io/packages/))

--------------------------------------------

I've just ran successful scans to verify the changes above, happy to provide more details and/or discuss further! Thanks for looking into this 😄

**Comment by janet-can** [comment]
Excellent, thank you for the corrections and additions, @artc95 !
